### ISSUE TITLE
zf2 2.0.5 not initialized.

### ISSUE THREAD

**Issue by Paul75** [phly/PhlyContact#4]
Hello,

When I want to use it and declare it to application.config.php and after launch the site it failed and the message is "Fatal error: Uncaught exception 'Zend\ModuleManager\Exception\RuntimeException' with message 'Module (phly) could not be initialized.'"

Why ?

**Comment by weierophinney** [comment]
How are you adding it to application.config.php? The entry there should be
simply "PhlyContact"; I suspect you used the string "phly/phly-contact" or
similar.

On Tuesday, December 18, 2012, Paul wrote:

> Hello,
> 
> When I want to use it and declare it to application.config.php and after
> launch the site it failed and the message is "Fatal error: Uncaught
> exception 'Zend\ModuleManager\Exception\RuntimeException' with message
> 'Module (phly) could not be initialized.'"
> 
> Why ?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/weierophinney/PhlyContact/issues/4.

## 

Matthew Weier O'Phinney
matthew@weierophinney.net
http://mwop.net/

**Comment by Paul75** [comment]
Hello,

Okay you are right :)

Sorry

**Comment by DeanHarber** [comment]
I have the same problem. Module (PhlyContact) could not be initialized. I suspect it has to do with vendor/ZF2 instead of vendor/zendframework/zendframework. Can anyone assist?
